[package]
name = "fiveetoolsapi"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
axum-server = "0.7.1"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0.217", features = ["derive"] }
